### ISSUE TITLE
not working on ai 2021?

### ISSUE THREAD

**Issue by kemie** [Inventsable/Outliner#1]
This is just failing silently for me in the latest Illustrator. Is it just me?

**Comment by Inventsable** [comment]
Did it work in prior versions with the same file and art?

**Comment by kemie** [comment]
first time trying it, so I don't know. trying it out on simple rectangles and circles and it's just not producing any output.

**Comment by MattAppleton** [comment]
Hi there — amazing idea for a script, thanks so much! 

Unfortunately I cant get this to do anything in AI2022. A silent 'fail' as mentioned above...
I out the script into presets / scripts — nothing happens when I run the script via file/scripts...

**Comment by kemie** [comment]
@MattAppleton tip: the only script I've gotten to work is jooHandles to Geometry here:
https://bitbucket.org/joojaa/jooillustratorscripts/src/master/jooHandlesToGeometry.jsx

**Comment by Inventsable** [comment]
The main function was commented out at the time of this posting. Technically nothing was silently failing, there just wasn't any self-execution or invocation of the `main()` function for the script to actually run.
